name: publish-pdf
on: [push]                      # yamllint disable-line rule:truthy
jobs:
  publish-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: hpsf2025-pnanda.tex
          latexmk_use_lualatex: true
      - uses: softprops/action-gh-release@v2
        with:
          name: hpsf2025-pnanda.pdf
          files: hpsf2025-pnanda.pdf
