name: create-pdfs
run-name: ${{ github.actor }} is creating PDFs
on: [push]                      # yamllint disable-line rule:truthy
jobs:
  check-lualatex-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            hpsf2025-pnanda.tex
          latexmk_use_lualatex: true
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: hpsf2025-pnanda.pdf
